name: berry-economy
version: '1.0'
main: me.berrycraft.berryeconomy.Berry
api-version: '1.20'
commands:
  exchange:
    usage: /exchange
    description: exchange berries
  auction:
    usage: /auction
    description: open the auction house gui